### PR TITLE
Restore continuous integration

### PR DESCRIPTION
**Pull request by jayaddison**
As visible in one of the [build job logs](https://travis-ci.org/github/JulienPalard/textunwrap/jobs/761190716) from #2, continuous integration builds are failing.  This pull request aims to restore passing builds.

### CODE REVIEW

**Comment by jayaddison** [comment]
@JulienPalard Is `twine` only [required in `requirements_dev.txt`](https://github.com/JulienPalard/textunwrap/blob/2bd690e0d3160861ee978e62ba84633a1cc3219f/requirements_dev.txt#L11) for the Travis `deploy` step?

Although I've tried to fix the build process here by including Rust toolchain dependencies required to build `cryptography` (an indirect dependency of `twine` via `keyring`), I'm wondering if it might be possible and easier (and use less build time / resources) to only install `twine` (possibly using prebuilt binary wheels) before the `deploy` step takes place.

Edit: fixup: keychain -> keyring

**Comment by JulienPalard** [comment]
I think bumping `pip` is enough to get a cryptography wheel, I'm trying it.

Wow py33, it's an old project :D

**Comment by JulienPalard** [comment]
I migrated to Github actions while I'm at it.

So yes, next time you're having a cryptography/rust issue, just `python -m pip install --upgrade pip`, it should be enough, a recent pip will pick a cryptography wheel instead of building it from sources (rust is a compile-time dependency, not a run-time dependency).

**Comment by jayaddison** [comment]
Excellent, thank you!

**Pull request closed without merging**
